name: Deploy LGP to Sepolia & Base Sepolia

on:
  workflow_dispatch: {}
  push:
    branches: [ ai/lgp-mvp ]
    paths:
      - "contracts/**"
      - "scripts/**"
      - ".github/workflows/deploy-testnets.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Mirror secrets into env so we can reference env.* in `if:` conditions
    env:
      L1_RPC_URL: ${{ secrets.L1_RPC_URL }}
      L2_RPC_URL: ${{ secrets.L2_RPC_URL }}
      DEPLOYER_KEY: ${{ secrets.DEPLOYER_KEY }}
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          ~/.foundry/bin/foundryup
          echo "$HOME/.foundry/bin" >> $GITHUB_PATH

      - name: Cache forge lib
        uses: actions/cache@v4
        with:
          path: lib
          key: forge-lib-${{ hashFiles('foundry.toml') }}

      - name: Install forge deps (forge-std)
        run: |
          if [ ! -d lib/forge-std ]; then forge install foundry-rs/forge-std@v1.9.3 --no-commit; fi

      - name: Build & test
        run: forge test -vvv

      - name: Ensure scripts dir
        run: mkdir -p scripts

      - name: Install ts-node (for record-addresses.ts)
        run: npm i -g ts-node typescript

      # ---------- L1 (Sepolia) ----------
      - name: Deploy L1 (Sepolia)
        if: ${{ env.L1_RPC_URL != '' && env.DEPLOYER_KEY != '' }}
        run: |
          forge script scripts/Deploy_L1.s.sol \
            --rpc-url "$L1_RPC_URL" \
            --private-key "$DEPLOYER_KEY" \
            --broadcast ${ETHERSCAN_API_KEY:+--verify}

      - name: Record L1 addresses
        if: ${{ env.L1_RPC_URL != '' && env.DEPLOYER_KEY != '' }}
        run: |
          if [ -f scripts/deploy-l1.json ]; then
            ts-node scripts/record-addresses.ts scripts/deploy-l1.json
          else
            echo "deploy-l1.json not found (skipping)"
          fi

      # ---------- L2 (Base Sepolia) ----------
      - name: Deploy L2 (Base Sepolia)
        if: ${{ env.L2_RPC_URL != '' && env.DEPLOYER_KEY != '' }}
        run: |
          forge script scripts/Deploy_L2.s.sol \
            --rpc-url "$L2_RPC_URL" \
            --private-key "$DEPLOYER_KEY" \
            --broadcast

      - name: Record L2 addresses
        if: ${{ env.L2_RPC_URL != '' && env.DEPLOYER_KEY != '' }}
        run: |
          if [ -f scripts/deploy-l2.json ]; then
            ts-node scripts/record-addresses.ts scripts/deploy-l2.json
          else
            echo "deploy-l2.json not found (skipping)"
          fi

      - name: Upload addresses.json
        uses: actions/upload-artifact@v4
        with:
          name: lgp-addresses
          path: scripts/addresses.json
          if-no-files-found: warn
