name: Deploy LGP to Sepolia & Base Sepolia

on:
  workflow_dispatch: {}
  push:
    branches: [ ai/lgp-mvp ]
    paths:
      - "contracts/**"
      - "script/**"
      - ".github/workflows/deploy-testnets.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          ~/.foundry/bin/foundryup
          echo "$HOME/.foundry/bin" >> $GITHUB_PATH

      - name: Cache lib
        uses: actions/cache@v4
        with:
          path: lib
          key: forge-lib-${{ hashFiles('foundry.toml') }}

      - name: Install forge deps
        run: |
          if [ ! -d lib/forge-std ]; then forge install foundry-rs/forge-std@v1.9.3 --no-commit; fi

      - name: Build & test
        run: forge test -vvv

      # -------- Sepolia (L1) --------
      - name: Deploy L1 (Sepolia)
        env:
          RPC_URL: ${{ secrets.L1_RPC_URL }}
          PK: ${{ secrets.DEPLOYER_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: |
          forge script scripts/Deploy_L1.s.sol \
            --rpc-url "$RPC_URL" \
            --private-key "$PK" \
            --broadcast ${ETHERSCAN_API_KEY:+--verify}

      - name: Record L1 addresses
        run: |
          npm i -g ts-node typescript
          ts-node scripts/record-addresses.ts scripts/deploy-l1.json

      # -------- Base Sepolia (L2) --------
      - name: Deploy L2 (Base Sepolia)
        env:
          RPC_URL: ${{ secrets.L2_RPC_URL }}
          PK: ${{ secrets.DEPLOYER_KEY }}
        run: |
          forge script scripts/Deploy_L2.s.sol \
            --rpc-url "$RPC_URL" \
            --private-key "$PK" \
            --broadcast

      - name: Record L2 addresses
        run: |
          ts-node scripts/record-addresses.ts scripts/deploy-l2.json

      - name: Upload addresses.json
        uses: actions/upload-artifact@v4
        with:
          name: lgp-addresses
          path: scripts/addresses.json
          if-no-files-found: warn

